package coursework.command;

public enum ClientAction {
    CHECK_IF_ACCOUNT_EXIST, LOGIN, CHANGE_PASSWORD, REGISTRATION,
    UPDATE_USER, CHECK_IF_ID_EXIST, SAVE_BOOK,
    DELETE_STUDENT_RECORD, DELETE_STUDENT, LOAD_DATA,
    UN_ARCHIVE_RECORD, LOAD_ARCHIEVED_RECORD, FETCH_USERNAME,
    UPDATE_ADMIN_INFO, LOAD_ADMIN_INFO,
    CHECK_IF_ACCOUNT_ALREADY_EXIST, DELETE_LIBRARIAN, CHECK_IF_USERNAME_EXISTS,
    LOAD_DATA_LIBRARIAN, UPDATE_LIBRARIAN, GET_DATA, SEARCH_BOOK, SEARCH_STUDENT, CHECK_LATE_FEE, CHECK_IF_STUDENT_OWNS_BOOK, SEARCH_BOOK_BY_BOOKID, SELECT_SHORT_TERM_BORROWED_TIME, INSERT_INTO_BOOK, CHANGE_AVAILABILITY_IN_BOOK_ENTITY, COUNT_OF_REMAINING_BOOKS, UPDATE_REMAINING_BOOKS, SAVE_LIBRARIAN


}
